/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package be.ehb.multec.groep5;

import be.ehb.multec.groep5.Extra.*;
import be.ehb.multec.groep5.SapMachine.*;
import be.ehb.multec.groep5.sap.*;

import java.awt.event.ActionEvent;
import java.util.ArrayList;

/**
 *
 * @author Yassi
 */
public class VruchtensapAutomaatGUI extends javax.swing.JFrame {

    /**
     * Creates new form VruchtensapAutomaatGUI
     */
    public VruchtensapAutomaatGUI() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        canvas1 = new java.awt.Canvas();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        firstPanel3 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        fruitsapPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        suikerPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        waterPanel = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        formaatPanel = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        choisePanell = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        totaalPanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        totaalPrijsLbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        menuList = new javax.swing.JList<>();
        nextButtonPanel = new javax.swing.JPanel();
        nextBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(700, 700));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 500));

        firstPanel3.setToolTipText("");
        firstPanel3.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel33.setFont(new java.awt.Font("Pixel Emulator", 1, 18)); // NOI18N
        jLabel33.setText("Maak een keuze. ");

        buttonGroup1.add(jRadioButton21);
        jRadioButton21.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton21.setText("Fruitsap");
        jRadioButton21.setActionCommand("");
        jRadioButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton22);
        jRadioButton22.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton22.setText("Gepersonaliseerd");
        jRadioButton22.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout firstPanel3Layout = new javax.swing.GroupLayout(firstPanel3);
        firstPanel3.setLayout(firstPanel3Layout);
        firstPanel3Layout.setHorizontalGroup(
            firstPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, firstPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, firstPanel3Layout.createSequentialGroup()
                        .addComponent(jRadioButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233, Short.MAX_VALUE)
                        .addComponent(jRadioButton22)))
                .addContainerGap())
        );
        firstPanel3Layout.setVerticalGroup(
            firstPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(249, 249, 249)
                .addGroup(firstPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton22)
                    .addComponent(jRadioButton21))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab1", firstPanel3);
        firstPanel3.getAccessibleContext().setAccessibleName("firstPanel");

        fruitsapPanel.setToolTipText("");
        fruitsapPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        fruitsapPanel.setEnabled(false);
        fruitsapPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel3.setFont(new java.awt.Font("Pixel Emulator", 1, 18)); // NOI18N
        jLabel3.setText("kies uw sap");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton3.setText("Sinaasapelsap");
        jRadioButton3.setActionCommand("");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton4.setText("citroensap");
        jRadioButton4.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton5.setText("ananassap");
        jRadioButton5.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton6.setText("appelsap");
        jRadioButton6.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton7.setText("cocosap");
        jRadioButton7.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton7ActionPerformed(evt);
            }
        });

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton8.setText("perziksap");
        jRadioButton8.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fruitsapPanelLayout = new javax.swing.GroupLayout(fruitsapPanel);
        fruitsapPanel.setLayout(fruitsapPanelLayout);
        fruitsapPanelLayout.setHorizontalGroup(
            fruitsapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fruitsapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fruitsapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fruitsapPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fruitsapPanelLayout.createSequentialGroup()
                        .addGroup(fruitsapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton5))
                        .addGap(32, 32, 32)
                        .addGroup(fruitsapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fruitsapPanelLayout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(jRadioButton6)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fruitsapPanelLayout.createSequentialGroup()
                                .addComponent(jRadioButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                                .addComponent(jRadioButton7)
                                .addGap(57, 57, 57))))))
        );
        fruitsapPanelLayout.setVerticalGroup(
            fruitsapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fruitsapPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187)
                .addGroup(fruitsapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fruitsapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton3)
                        .addComponent(jRadioButton4))
                    .addComponent(jRadioButton6))
                .addGap(186, 186, 186)
                .addGroup(fruitsapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fruitsapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButton7)
                        .addComponent(jRadioButton8))
                    .addComponent(jRadioButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", fruitsapPanel);
        fruitsapPanel.getAccessibleContext().setAccessibleName("fruitsapPanel");

        suikerPanel.setToolTipText("");
        suikerPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel11.setFont(new java.awt.Font("Pixel Emulator", 1, 18)); // NOI18N
        jLabel11.setText("suiker of suikervrij ");

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton9.setText("suiker");
        jRadioButton9.setActionCommand("");
        jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton9ActionPerformed(evt);
            }
        });

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton10.setText("zonder suiker");
        jRadioButton10.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout suikerPanelLayout = new javax.swing.GroupLayout(suikerPanel);
        suikerPanel.setLayout(suikerPanelLayout);
        suikerPanelLayout.setHorizontalGroup(
            suikerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suikerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(suikerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(suikerPanelLayout.createSequentialGroup()
                        .addComponent(jRadioButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton10))
                    .addGroup(suikerPanelLayout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 216, Short.MAX_VALUE)))
                .addContainerGap())
        );
        suikerPanelLayout.setVerticalGroup(
            suikerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(suikerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(237, 237, 237)
                .addGroup(suikerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton9)
                    .addComponent(jRadioButton10))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", suikerPanel);

        waterPanel.setToolTipText("");
        waterPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel17.setFont(new java.awt.Font("Pixel Emulator", 1, 18)); // NOI18N
        jLabel17.setText("plat water of bruiswater?");

        buttonGroup4.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton13.setText("plat water");
        jRadioButton13.setActionCommand("");
        jRadioButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton13ActionPerformed(evt);
            }
        });

        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton14.setText("bruiswater");
        jRadioButton14.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout waterPanelLayout = new javax.swing.GroupLayout(waterPanel);
        waterPanel.setLayout(waterPanelLayout);
        waterPanelLayout.setHorizontalGroup(
            waterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(waterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(waterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 150, Short.MAX_VALUE))
                    .addGroup(waterPanelLayout.createSequentialGroup()
                        .addComponent(jRadioButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton14)))
                .addContainerGap())
        );
        waterPanelLayout.setVerticalGroup(
            waterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(waterPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242)
                .addGroup(waterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton14)
                    .addComponent(jRadioButton13))
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", waterPanel);
        waterPanel.getAccessibleContext().setAccessibleName("waterPanel");

        formaatPanel.setToolTipText("");
        formaatPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel20.setFont(new java.awt.Font("Pixel Emulator", 1, 18)); // NOI18N
        jLabel20.setText("groot formaat of klein formaat");

        buttonGroup5.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton15.setText("Groot formaat");
        jRadioButton15.setActionCommand("");
        jRadioButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton15ActionPerformed(evt);
            }
        });

        buttonGroup5.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton16.setText("klein formaat");
        jRadioButton16.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formaatPanelLayout = new javax.swing.GroupLayout(formaatPanel);
        formaatPanel.setLayout(formaatPanelLayout);
        formaatPanelLayout.setHorizontalGroup(
            formaatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formaatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formaatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formaatPanelLayout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 104, Short.MAX_VALUE))
                    .addGroup(formaatPanelLayout.createSequentialGroup()
                        .addComponent(jRadioButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton16)))
                .addContainerGap())
        );
        formaatPanelLayout.setVerticalGroup(
            formaatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formaatPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(229, 229, 229)
                .addGroup(formaatPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton15)
                    .addComponent(jRadioButton16))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab5", formaatPanel);
        formaatPanel.getAccessibleContext().setAccessibleName("formaatPanel");

        choisePanell.setToolTipText("");
        choisePanell.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel23.setFont(new java.awt.Font("Pixel Emulator", 1, 18)); // NOI18N
        jLabel23.setText("betalen of een ander sapje bestellen?");

        buttonGroup6.add(jRadioButton17);
        jRadioButton17.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton17.setText("Betalen");
        jRadioButton17.setActionCommand("");
        jRadioButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton17ActionPerformed(evt);
            }
        });

        buttonGroup6.add(jRadioButton18);
        jRadioButton18.setFont(new java.awt.Font("Pixel Emulator", 0, 14)); // NOI18N
        jRadioButton18.setText("ANder sap");
        jRadioButton18.setActionCommand("Gepersonaliseerd Fruitsap");
        jRadioButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout choisePanellLayout = new javax.swing.GroupLayout(choisePanell);
        choisePanell.setLayout(choisePanellLayout);
        choisePanellLayout.setHorizontalGroup(
            choisePanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choisePanellLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(choisePanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(choisePanellLayout.createSequentialGroup()
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, choisePanellLayout.createSequentialGroup()
                        .addComponent(jRadioButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButton18)
                        .addGap(21, 21, 21))))
        );
        choisePanellLayout.setVerticalGroup(
            choisePanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choisePanellLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236)
                .addGroup(choisePanellLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton18)
                    .addComponent(jRadioButton17))
                .addContainerGap(167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab6", choisePanell);
        choisePanell.getAccessibleContext().setAccessibleName("choisePanel");

        totaalPanel.setToolTipText("");
        totaalPanel.setPreferredSize(new java.awt.Dimension(500, 500));

        jLabel26.setFont(new java.awt.Font("Pixel Emulator", 1, 18)); // NOI18N
        jLabel26.setText("te betalen");

        jLabel14.setFont(new java.awt.Font("Pixel Emulator", 0, 18)); // NOI18N
        jLabel14.setText("Menu");

        totaalPrijsLbl.setFont(new java.awt.Font("Pixel Emulator", 0, 18)); // NOI18N
        totaalPrijsLbl.setText("€");

        jLabel16.setFont(new java.awt.Font("Pixel Emulator", 0, 18)); // NOI18N
        jLabel16.setText("Totaal");

        jLabel36.setFont(new java.awt.Font("Pixel Emulator", 0, 18)); // NOI18N
        jLabel36.setText("prijs");

        menuList.setFont(new java.awt.Font("Nikkyou Sans", 0, 14)); // NOI18N
        menuList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(menuList);

        javax.swing.GroupLayout totaalPanelLayout = new javax.swing.GroupLayout(totaalPanel);
        totaalPanel.setLayout(totaalPanelLayout);
        totaalPanelLayout.setHorizontalGroup(
            totaalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totaalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(totaalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(totaalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totaalPanelLayout.createSequentialGroup()
                            .addGroup(totaalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(totaalPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totaalPrijsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(totaalPanelLayout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(7, 7, 7)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        totaalPanelLayout.setVerticalGroup(
            totaalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(totaalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(totaalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(totaalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totaalPrijsLbl)
                    .addComponent(jLabel16))
                .addGap(61, 61, 61))
        );

        jTabbedPane1.addTab("tab7", totaalPanel);
        totaalPanel.getAccessibleContext().setAccessibleName("totaalPanel");

        nextButtonPanel.setFont(new java.awt.Font("Pixel Emulator", 1, 12)); // NOI18N

        nextBtn.setFont(new java.awt.Font("Pixel Emulator", 0, 12)); // NOI18N
        nextBtn.setText("Next");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nextButtonPanelLayout = new javax.swing.GroupLayout(nextButtonPanel);
        nextButtonPanel.setLayout(nextButtonPanelLayout);
        nextButtonPanelLayout.setHorizontalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextButtonPanelLayout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        nextButtonPanelLayout.setVerticalGroup(
            nextButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nextButtonPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(nextBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextButtonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //variables

    public int tabbel = 0;

    public int menuNum = 0;

    Fruitsap fruitsap;
    MainSap mainSap;

    public ArrayList<String> dataMenu = new ArrayList<>();

    public double totaalPrijs;

    public static Menu menu = Menu.getInstance();

    
    
    private void nextBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBtnActionPerformed
        // TODO add your handling code here:
        
        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
        
    }//GEN-LAST:event_nextBtnActionPerformed


    //Ander Fruitsap evt
    private void jRadioButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton18ActionPerformed
        // TODO add your handling code here:

        //prijs van de menu(sap) bereken
        menu.prijs = Math.round(menu.prijs*100.0)/100.0;

        totaalPrijs += menu.prijs;

        //array voor gekozen sap
        String[] eenMenu = {
                "Menu " + (menuNum+1),
                menu.fruitsapName, "suiker: " + menu.suiker,
                "water: " + menu.water,
                "formaat: " + menu.formaat + "ml",
                menu.prijs + "€", "------------"
        };
        
        //item in menu array toevoegen
        for(String item : eenMenu){

            dataMenu.add(item);

        }

        System.out.println(dataMenu);
        
        menuList.setListData(dataMenu.toArray(new String[0]));

        menuNum +=1;

         jTabbedPane1.setSelectedIndex(0);


         mainSap.start(menu.suiker, menu.water);


    }//GEN-LAST:event_jRadioButton18ActionPerformed


    //betalen evt
    private void jRadioButton17ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jRadioButton17ActionPerformed
        // TODO add your handling code here:

        //prijs van de menu(sap) berekenen
        menu.prijs = Math.round(menu.prijs*100.0)/100.0;

        //array voor elke gekozen sap
        String[] eenMenu = {
                "Menu " + (menuNum+1),
                menu.fruitsapName, "suiker: " + menu.suiker,
                "water: " + menu.water,
                "formaat: " + menu.formaat + "ml",
                menu.prijs + " €"
        };
        //item in menu array toevoegen
        for(String item : eenMenu){
            dataMenu.add(item);
        }


        System.out.println(dataMenu);
        menuList.setListData(dataMenu.toArray(new String[0]));

        //totaalPtijs
        totaalPrijs += menu.prijs;

        totaalPrijs =  Math.round(totaalPrijs*100.0)/100.0;

        totaalPrijsLbl.setText(totaalPrijs + " €");

        mainSap.start(menu.suiker, menu.water);
        
        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);


    }//GEN-LAST:event_jRadioButton17ActionPerformed

    //Klein Formaat Radio btn functie
    private void jRadioButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton16ActionPerformed
        // TODO add your handling code here:
        fruitsap = new KleinFormaat(fruitsap);
        menu.formaat = fruitsap.formaat();
        menu.prijs += fruitsap.cost();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton16ActionPerformed

    //Groot Formaat Radio btn functie
    private void jRadioButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton15ActionPerformed
        // TODO add your handling code here:

        fruitsap = new GrootFormaat(fruitsap);
        menu.formaat = fruitsap.formaat();
        menu.prijs += fruitsap.cost();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton15ActionPerformed

    //Bruiswater Radio btn functie
    private void jRadioButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton14ActionPerformed
        // TODO add your handling code here:
        fruitsap = new Bruiswater(fruitsap);

        menu.water = fruitsap.getFruitsapName();
        menu.prijs += fruitsap.cost();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton14ActionPerformed

    //plat water Radio btn functie
    private void jRadioButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton13ActionPerformed
        // TODO add your handling code here:

        fruitsap = new PlatWater(fruitsap);

        menu.water = fruitsap.getFruitsapName();
        menu.prijs += fruitsap.cost();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton13ActionPerformed

    //ZonderSuiker Radio btn functie
    private void jRadioButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton10ActionPerformed
        // TODO add your handling code here:

        fruitsap = new ZonderSuiker(fruitsap);

        menu.suiker = fruitsap.getFruitsapName();
        menu.prijs += fruitsap.cost();
        
        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton10ActionPerformed

    //zonder Suiker Radio btn functie
    private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton9ActionPerformed
        // TODO add your handling code here:
        fruitsap = new Suiker(fruitsap);

        menu.suiker = fruitsap.getFruitsapName();
        menu.prijs += fruitsap.cost();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton9ActionPerformed


    /***************************  FruitSap  **************************/

    ///Perziksap Evt
    private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton8ActionPerformed
        // TODO add your handling code here:

        fruitsap = new Perziksap();
        menu.fruitsapName = fruitsap.fruitsapName;
        menu.prijs = fruitsap.cost();

        mainSap = new PerzikFruit();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton8ActionPerformed



    //Cocosap Evt
    private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton7ActionPerformed
        // TODO add your handling code here:

        fruitsap = new Cocosap();
        menu.fruitsapName = fruitsap.fruitsapName;
        menu.prijs = fruitsap.cost();

        mainSap = new CocoFruit();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton7ActionPerformed

    //Appelsap Evt
    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
        fruitsap = new Appelsap();
        menu.fruitsapName = fruitsap.fruitsapName;
        menu.prijs = fruitsap.cost();

        mainSap = new AppelFruit();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    //Ananassap Evt
    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
        fruitsap = new Ananassap();
        menu.fruitsapName = fruitsap.fruitsapName;
        menu.prijs = fruitsap.cost();

        mainSap = new AnanaFruit();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    //Citroensap Evt
    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
        fruitsap = new Citroensap();
        menu.fruitsapName = fruitsap.fruitsapName;
        menu.prijs = fruitsap.cost();

        mainSap = new CitroenFruit();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton4ActionPerformed


    //sinaasappelsap evt
    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        fruitsap = new Sinaasapelsap();
        menu.fruitsapName = fruitsap.fruitsapName;
        menu.prijs = fruitsap.cost();

        mainSap = new SinaasapelFruit();

        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton3ActionPerformed


    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
        //volgende pagina  
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    //Fruitsap Evt
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        menu.bestelling = "Fruitsap";    
        
        //volgende pagina 
        tabbel = jTabbedPane1.getSelectedIndex();
        jTabbedPane1.setSelectedIndex(tabbel == jTabbedPane1.getTabCount()-1 ? 0 : tabbel + 1);
        
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VruchtensapAutomaatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VruchtensapAutomaatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VruchtensapAutomaatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VruchtensapAutomaatGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VruchtensapAutomaatGUI().setVisible(true);
               
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private java.awt.Canvas canvas1;
    private javax.swing.JPanel choisePanell;
    private javax.swing.JPanel firstPanel3;
    private javax.swing.JPanel formaatPanel;
    private javax.swing.JPanel fruitsapPanel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> menuList;
    private javax.swing.JButton nextBtn;
    private javax.swing.JPanel nextButtonPanel;
    private javax.swing.JPanel suikerPanel;
    private javax.swing.JPanel totaalPanel;
    private javax.swing.JLabel totaalPrijsLbl;
    private javax.swing.JPanel waterPanel;
    // End of variables declaration//GEN-END:variables
}
